services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8448:8448
    environment:
      DOMAIN: ${DOMAIN}
      TZ: ${TZ}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      MAILNAME: ${DOMAIN}

  tuwunel:
    container_name: tuwunel
    image: jevolk/tuwunel:latest
    restart: unless-stopped
    volumes:
        - tuwunel-data:/var/lib/tuwunel
    environment:
        TUWUNEL_SERVER_NAME: ${SERVER_NAME}
        TUWUNEL_TRUSTED_SERVERS: '["matrix.org"]'
        TUWUNEL_FORGET_FORCED_UPON_LEAVE: true
        TUWUNEL_LOCKDOWN_PUBLIC_ROOM_DIRECTORY: true
        TUWUNEL_ALLOW_ROOM_CREATION: false
        TUWUNEL_ADDRESS: 0.0.0.0

        TUWUNEL_LDAP__ENABLE: true
        TUWUNEL_LDAP__URI: "ldap://lldap:3890"
        TUWUNEL_LDAP__BASE_DN: "ou=people,dc=pona,dc=la"
        TUWUNEL_LDAP__BIND_DN: "cn=admin,ou=people,dc=pona,dc=la"
        TUWUNEL_LDAP__BIND_PASSWORD_FILE: "/run/secrets/ldap_bind_password"
        TUWUNEL_LDAP__UID_ATTRIBUTE: "uid"
        TUWUNEL_LDAP__MAIL_ATTRIBUTE: "mail"
        TUWUNEL_LDAP__NAME_ATTRIBUTE: "cn"
        TUWUNEL_LDAP__ADMIN_FILTER: "(memberOf=cn=matrix_admin,ou=groups,dc=pona,dc=la)"
    secrets:
      - ldap_bind_password
  ooye:
    image: ghcr.io/katharostech/ooye:master
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_ORIGIN: http://tuwunel:8008
      ADMIN_INVITE: "@admin:pona.la"
      URL: https://bridge.${DOMAIN}
      HS_TOKEN: ${OOYE_HS_TOKEN}
      AS_TOKEN: ${OOYE_AS_TOKEN}
      DISCORD_TOKEN: ${OOYE_BOT_TOKEN}
    volumes:
      - ooye-data:/data
  lldap:
    image: lldap/lldap:stable
    volumes:
      - "lldap-data:/data"
    environment:
      TZ: ${TZ}
      LLDAP_JWT_SECRET: ${LDAP_JWT_SECRET}
      LLDAP_KEY_SEED: ${LDAP_KEY_SEED}
      LLDAP_LDAP_BASE_DN: dc=pona,dc=la
      LLDAP_LDAP_USER_PASS: ${LDAP_ADMIN_PASS}
      LLDAP_KEY_FILE: ""

      LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
      LLDAP_SMTP_OPTIONS__SERVER: mail
      LLDAP_SMTP_OPTIONS__PORT: 25
      LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: NONE
      LLDAP_SMTP_OPTIONS__FROM: no-reply <no-reply@${DOMAIN}>
      LLDAP_SMTP_OPTIONS__TO: Nikolas Lehto <nikolas@testausserveri.fi>
    command: "send_test_email --to=nikolas@testausserveri.fi --verbose"
    depends_on:
      - mail

# This stores the LDAP password as a file in the tuwunel container as required by tuwunel's LDAP configuration.
secrets:
  ldap_bind_password:
    environment: LDAP_ADMIN_PASS

volumes:
  caddy-data:
  caddy-config:
  tuwunel-data:
  lldap-data:
  ooye-data:

networks:
  tuwunel-caddy:
