issuer: http://mi.pona.la/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

# HTTP service configuration
web:
  http: 0.0.0.0:5556
  # Dex UI configuration
  # frontend:
  issuer: mi pona
  logoURL: /register/static/logo.png
  dir: ""
  theme: light

logger:
  level: "info"
  format: "json"
  # TODO: Consider excluding certain fields for GDPR compliance.
  # Drop these attribute keys from all log output (useful for GDPR/PII suppression).
  #excludeFields: [email, username, preferred_username, groups]

staticClients:
  - name: 'ilo Kito'
    id: ilo-kito
    secretEnv: ILO_KITO
    redirectURIs:
      - 'https://kito.pona.la/user/oauth2/mi%20pona/callback'


connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: lldap:3890
      insecureNoSSL: true
      insecureSkipVerify: true
      bindDN: uid=admin,ou=people,dc=mi,dc=pona,dc=la
      bindPW: $LDAP_ADMIN_PASS
      userSearch:
        baseDN: ou=people,dc=mi,dc=pona,dc=la
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: displayName
        preferredUsernameAttr: uid
      groupSearch:
        baseDN: ou=groups,dc=mi,dc=pona,dc=la
        filter: "(objectClass=groupOfUniqueNames)"
        userMatchers:
          - userAttr: DN
            groupAttr: member
        nameAttr: cn
